name: newtfapply
on: 
  workflow_dispatch:
  workflow_call:
    
  #  inputs: 
  #     choose-env: 
  #      description: test
  #      required: true
  #      type: string
  #      default: dev
env: 
 ARM_TENANT_ID: "17a09c66-f406-4897-8b24-51f5313623dc"
 ARM_CLIENT_ID      : "6589b09f-b35e-4dd2-86fc-d7a757d9f72e"
 ARM_CLIENT_SECRET   : "NJY8Q~FE5ufe-fbK4Dlb6tzT8WNA9pvbl-nYlc-3" 
 TF_WORKSPACE : "api-workspace"
 TF_TOKEN_app_terraform_io : "${{ secrets.TF_API_TOKEN }}"
#  TF_API_TOKEN : "Es59plk79rxzCQ.atlasv1.DeGIp7BOagPyZFkN3Xfs1cC5mt4CG0OxnMIvJ8gOyHfpy16CK7bctQSBZhpUw9AerSA"     
permissions:
 id-token: write
 contents: read

jobs: 
  terra_validate: 
    runs-on: ubuntu-latest
    name: terraform_validate_job
    # environment: dev
    steps:

     - name: Checkout
       uses: actions/checkout@v3

     - name: terraform_validate
       working-directory: ./terraform
       run: |
         terraform init
         terraform validate

  terra_plan: 
    runs-on: ubuntu-latest
    name: terraform_plan_job
    # environment: dev
    
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: terraform_plan
       working-directory: ./terraform
       run: |
         terraform init
         terraform plan

  terra_apply: 
    runs-on: ubuntu-latest
    name: terraform_apply_job
    environment: dev
    
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: terraform_apply
       working-directory: ./terraform
       run: |
         terraform init
         terraform apply --auto-approve
